### ISSUE TITLE
Extending Markdown

### ISSUE THREAD

**Issue by flamusdiu** [singingwolfboy/flask-misaka#13]
Is there a way to add extra tags to Markdown? I can't seem to find away to take something like "[mytag]text[/mytag]" and get "<p>text</p>" (or any other html tags). Maybe I am trying too hard. =P

**Comment by singingwolfboy** [comment]
That seems like a question to ask on the Misaka project: https://github.com/FSX/misaka However, I don't believe that Misaka supports adding arbitrary extra tags to Markdown.
