### ISSUE TITLE
Misaka extensions don't seem to work

### ISSUE THREAD

**Issue by flamusdiu** [singingwolfboy/flask-misaka#14]
I can't seem to get any of the extensions to work. 

I am doing something like this:

```
app = Flask(__name__)
Misaka(app, ext=('footnotes', 'tables')) 
```
However, this doesn't seem to work. Unless my syntax is wrong with in Markdown or python.

**Comment by flamusdiu** [comment]
Never mind, you need to do:
```
Misaka(app, footnotes=True, tables=True)
```
=P

**Comment by singingwolfboy** [comment]
Is there a way we could make this clearer in the documentation? If you were confused, other people will be confused, as well.

**Comment by flamusdiu** [comment]
@singingwolfboy yeah, that's why I am checking how to do things to work properly. at first, I thought the `make_options()` function was not working right. I just realized I wasn't using `Misaka()` properly.

**Comment by singingwolfboy** [comment]
The automated tests also should provide some examples of how to call Flask-Misaka properly.

**Comment by flamusdiu** [comment]
Rgr. Let me work on the documentation and then we can get the tests setup.

**Comment by balestrieri** [comment]
For me too it was difficult to find out the right way to set the options from the documentation. Just to let you know so that the documentation could be improved. Thank you!
