### ISSUE TITLE
escape html in markdown

### ISSUE THREAD

**Issue by stsouko** [singingwolfboy/flask-misaka#17]
escape=True, html=False don't work then I use custom renderer inherited from misaka.HtmlRenderer.

**Comment by singingwolfboy** [comment]
@stsouko Could you please provide an example? Please include:
* How you configure Flask-Misaka
* The Markdown you pass it
* The HTML that you _expect_ to see as a result
* The HTML that you _actually_ see as a result

**Comment by stsouko** [comment]
class CustomMisakaRenderer(HtmlRenderer):
    def table(self, content):
        return '<table class="table">{}</table>'.format(content)

Misaka(app, renderer=CustomMisakaRenderer(), escape=True,
           underline=True, math=True, strikethrough=True, superscript=True, tables=True, footnotes=True)

passed: *blah* <script>alert('!');</script>
expected: escape script
actually: get message box.

**Comment by pasqu4le** [comment]
this doesn't work indeed, but I think I've found a workaround.
You can use:

> Misaka(app, renderer=CustomMisakaRenderer(flags=**misaka.HTML_ESCAPE**), underline=True, math=True, strikethrough=True, superscript=True, tables=True, footnotes=True)

this worked for me.
You can set more than a flag using the | operator. 

Misaka Html flags can be found [in the documentation](http://misaka.61924.nl/#html-render-flags).

**Comment by stsouko** [comment]
Thank You! 
I've already done that way.

**Comment by singingwolfboy** [comment]
Looks like this is not a problem with the Flask-Misaka library -- the renderer will escape HTML only if you ask it to. As a result, I'm going to close this issue.
