### ISSUE TITLE
Unexplained behavior during a build step using pip install -r

### ISSUE THREAD

**Issue by wgwz** [singingwolfboy/flask-misaka#20]
Hey, @singingwolfboy. Really enjoying working with Flask-Misaka so far. 

So I'm using docker and docker-compose to run my flask app. During the build step I am noticing some unexplained funky-ness. Here's the relevant segment of the stdout from a `pip install -r requirements.txt` step:

```
Collecting Flask-Misaka==0.4.1 (from -r requirements.txt (line 14))
  Downloading Flask_Misaka-0.4.1-py2-none-any.whl
...
...
...
Collecting misaka<3.0,>=2.0 (from Flask-Misaka==0.4.1->-r requirements.txt (line 14))
  Downloading misaka-2.0.0.tar.gz (121kB)
```

Note the last bit ^

Here is my `requirements.txt`:

```
Flask==0.11.1
gunicorn==19.6.0
pytest==3.0.5
psycopg2==2.6.1
Flask-SQLAlchemy==2.1
six==1.10.0
SQLAlchemy-Utils==0.32.9
Flask-WTF==0.12
Flask-Bootstrap==3.3.7.0
Flask-Nav==0.6
Flask-Misaka==0.4.1
Flask-Login==0.4.0
Flask-Moment==0.5.1
```

Ultimately, it's a non-issue bc it still works. But as a perfectionist I thought I would mention it. 

And here is what I end up with (Flask-Misaka-0.4.1 despite the "`Downloading misaka-2.0.0.tar.gz (121kB)`" above):

```
Installing collected packages: itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, Flask, gunicorn, py, pytest, psycopg2, SQLAlchemy, Flask-SQLAlchemy, six, SQLAlchemy-Utils, WTForms, Flask-WTF, dominate, visitor, Flask-Bootstrap, Flask-Nav, pycparser, cffi, misaka, Flask-Misaka, Flask-Login, Flask-Moment
Successfully installed Flask-0.11.1 Flask-Bootstrap-3.3.7.0 Flask-Login-0.4.0 Flask-Misaka-0.4.1 Flask-Moment-0.5.1 Flask-Nav-0.6 Flask-SQLAlchemy-2.1 Flask-WTF-0.12 Jinja2-2.8.1 MarkupSafe-0.23 SQLAlchemy-1.1.4 SQLAlchemy-Utils-0.32.9 WTForms-2.1 Werkzeug-0.11.13 cffi-1.9.1 click-6.6 dominate-2.3.1 gunicorn-19.6.0 itsdangerous-0.24 misaka-2.0.0 psycopg2-2.6.1 py-1.4.32 pycparser-2.17 pytest-3.0.5 six-1.10.0 visitor-0.1.3
```

I guess this is an obscure python packaging quirk.

**Comment by singingwolfboy** [comment]
Hi @wgwz, glad you're enjoying the library! Flask-Misaka depends on another Python module called [misaka](https://pypi.python.org/pypi/misaka), which is what you're seeing in that pip output. Flask-Misaka is currently at version 0.4.1, misaka is currently at version 2.0.0. That's why you're seeing the output you're seeing. Does that help clarify things?

**Comment by wgwz** [comment]
Definitely clarifies the situation! Wow, I feel a bit foolish now. :P
