### ISSUE TITLE
Misaka works fine using the Flask dev server - but throws errors when using Apache2/Mod_wsgi

### ISSUE THREAD

**Issue by qzorg** [singingwolfboy/flask-misaka#22]
Hello, I have an application that uses Misaka as a component. It works great when using the development server, but when I try to deploy it using Apache2 and mod_wsgi, I get an error on the line that imports Misaka. This looks to be a Misaka specific issue, which is why I am bringing it here, but if I am wrong please let me know. Here is the error:

> 

``
> [Sun May 13 00:22:46.545124 2018] [mpm_prefork:notice] [pid 3684] AH00163: Apache/2.4.33 (Unix) mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
> [Sun May 13 00:22:46.545180 2018] [core:notice] [pid 3684] AH00094: Command line: '/usr/sbin/httpd -d /var/www -f /etc/apache2/httpd.conf'
[Sun May 13 00:22:53.722608 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400] mod_wsgi (pid=3689): Target WSGI script '/var/www/flaskchan/app.wsgi' cannot be loaded as Python module.
[Sun May 13 00:22:53.722655 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400] mod_wsgi (pid=3689): Exception occurred processing WSGI script '/var/www/flaskchan/app.wsgi'.
[Sun May 13 00:22:53.722679 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400] Traceback (most recent call last):
[Sun May 13 00:22:53.722808 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/var/www/flaskchan/app.wsgi", line 7, in <module>
[Sun May 13 00:22:53.722894 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     from app import app as application
[Sun May 13 00:22:53.722912 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/var/www/flaskchan/app.py", line 4, in <module>
[Sun May 13 00:22:53.723068 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     from flask.ext.misaka import Misaka
[Sun May 13 00:22:53.723087 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/usr/lib/python2.7/site-packages/flask/exthook.py", line 62, in load_module
[Sun May 13 00:22:53.723154 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     __import__(realname)
[Sun May 13 00:22:53.723171 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/usr/lib/python2.7/site-packages/flask_misaka.py", line 5, in <module>
[Sun May 13 00:22:53.723243 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     import misaka
[Sun May 13 00:22:53.723264 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/usr/lib/python2.7/site-packages/misaka/__init__.py", line 3, in <module>
[Sun May 13 00:22:53.723306 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     from .api import *
[Sun May 13 00:22:53.723322 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/usr/lib/python2.7/site-packages/misaka/api.py", line 10, in <module>
[Sun May 13 00:22:53.723447 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     from .callbacks import python_callbacks, to_string
[Sun May 13 00:22:53.723465 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]   File "/usr/lib/python2.7/site-packages/misaka/callbacks.py", line 8, in <module>
[Sun May 13 00:22:53.723617 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400]     @ffi.callback('void(hoedown_buffer *ob, const hoedown_buffer *text, '
[Sun May 13 00:22:53.723643 2018] [wsgi:error] [pid 3689] [client 192.168.1.243:45400] SystemError: error return without exception set
ibsrv:/var/www/flaskchan# 
``

I am using Flask 0.10.1, Misaka 0.3.0 and apache2 2.4

**Comment by qzorg** [comment]
correction, I tried with misaka 0.3.0 and 0.4.1 and recieved the same issue.

**Comment by singingwolfboy** [comment]
If the issue is related to Misaka, please report it at the Misaka repo: https://github.com/FSX/misaka
