### ISSUE TITLE
Math doesn't render for me.

### ISSUE THREAD

**Issue by E-Wagner** [singingwolfboy/flask-misaka#25]
I'm creating a personal blog that requires support for latex. I'm using Flask-Misaka to achieve this. However it won't render the latex in my markdown file. Any idea how to do this?

**these are my routes. (where content contains $x+y$ or $$x+y$$)**
`from application import app
from flask import render_template
from flask_misaka import markdown

content=""
with open("./markdown/sampletext.md", "r") as f:
    content = f.read()
@app.route("/")
def index():
    return render_template("index.html", text=markdown(content, math=True))`

**And here is my init .py:**

`from flask import Flask
from flask_misaka import Misaka

app = Flask(__name__)
Misaka(app, math=True)

from application import routes`

In the index.html template I use: {{text | markdown}}
The mardown is working fine but it won't render the latex/math.

thank you for your time.

**Comment by singingwolfboy** [comment]
Hi @E-Wagner, I wonder if this is a problem with [Misaka](https://misaka.61924.nl/) itself, rather than Flask-Misaka. What happens if you try the following?

```python
import misaka

with open("./markdown/sampletext.md", "r") as f:
    content = f.read()

html = misaka.html(content, extensions=misaka.EXT_MATH)
print(html)
```

Does it transform your math in the way you expect?

**Comment by E-Wagner** [comment]
@singingwolfboy, thanks for your reply. It still doesn't render it. Any idea how I can proceed?

**Comment by singingwolfboy** [comment]
If that's the case, then the bug is not in Flask-Misaka. It's in Misaka itself, or one of the layers that it depends on (like [hoedown](https://github.com/hoedown/hoedown)).

You should file a bug report with Misaka, and see if you can get the issue resolved there, instead. Sorry I can't help you further.
