### ISSUE TITLE
Blocks other filters  

### ISSUE THREAD

**Issue by sidbelbase** [singingwolfboy/flask-misaka#27]
When using this package it blocks other filters, for example:

```py
def humanize(date_str):
    dt = arrow.get(date_str)
    return dt.humanize()

jinja2.filters.FILTERS['humanize'] = humanize
```

And, if I make this custom filter and several other filter using `jinja2.filters.FILTERS` it blocks all other filters beneath it:

**...**
`<small class="text-muted">{{ post.timestamp | humanize }}</small>`
**...**

I don't know if I should use `jinja2.filters.FILTERS` or not use this package at all

**Comment by singingwolfboy** [comment]
[Here is the line in the code that sets this filter.](https://github.com/singingwolfboy/flask-misaka/blob/master/flask_misaka.py#L107) You can see that it references `app.jinja_env.filters` -- I'm not sure what is this `jinja2.filters.FILTERS` object that you are referring to. [The Flask docs suggest using `app.jinja_env.filters` or the `template_filter` decorator.](https://flask.palletsprojects.com/en/1.1.x/templating/#registering-filters) Have you tried that?

**Comment by sidbelbase** [comment]
I don't know how but `jinja2.filters.FILTERS` just works, lol, I have tried `app.jinja_env.filters` in the past but couldn't make it work while working with blueprints or with cloud factory method, but will give a second look, thanks

**Comment by sidbelbase** [comment]
I tried the Flask docs way again but it throws the same error:

```py
def humanize(date_str):
    dt = arrow.get(date_str)
    return dt.humanize()


app.jinja_env.filters['humanize'] = humanize
```

```
< small class="text-muted">{{ feed.timestamp | humanize }}</small>
jinja2.exceptions.TemplateAssertionError: no filter named 'humanize'
```

**Comment by singingwolfboy** [comment]
I'm afraid I can't help you with that issue. Seems like the problem you're having is unrelated to Flask-Misaka, so I'm closing this issue.

**Comment by sidbelbase** [comment]
Sure, I had just found a solution, but this is **future fellows** who might stuck on this same problem:
 
When working with Flask app that uses Blueprints or factory method, it needs the great care and attention, either register it as a filter during `create_app` process or make sure you get it to register as a blueprint like in the example:

```py
@core.app_template_filter('int_date')
def format_datetime(date):
    utc_time = timezone("UTC")
    london_time = timezone("Europe/London")
    if date:
        return utc_time.localize(date).astimezone(london_time).strftime('%Y-%m-%d %H:%M')
    return date
```
Here **core** is a registered blueprint and through that, we can use `app_template_filter('any_name')`

So, I solved it by registering it a **blueprint**.

Like you said @singingwolfboy how did I make `jinja2.filters.FILTERS` to work, well I had stumbled into [this solution](https://stackoverflow.com/questions/8339899/jinja2-custom-filter-templateassertionerror-no-filter-named-format-number) in the past and carried on until I got really stuck with this extension, but though, thanks :)

You may now close this issue :)
